webtalk_init -webtalk_dir C:/Users/jhgsilva/FPGA_Projects/Tx_Blocks/Numerically_Controlled_Oscillator/Numerically_Controlled_Oscillator.sim/sim_1/behav/xsim/xsim.dir/main_wrapper_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Jun  6 17:25:10 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "f7f6c852-b95c-403f-bbaa-d0d4d126a12f" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "cfb7465fe3184dbf9dc809002ee5a31f" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "24" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2803 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "3" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.06_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "8488_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1580781254 -regid "" -xml C:/Users/jhgsilva/FPGA_Projects/Tx_Blocks/Numerically_Controlled_Oscillator/Numerically_Controlled_Oscillator.sim/sim_1/behav/xsim/xsim.dir/main_wrapper_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/jhgsilva/FPGA_Projects/Tx_Blocks/Numerically_Controlled_Oscillator/Numerically_Controlled_Oscillator.sim/sim_1/behav/xsim/xsim.dir/main_wrapper_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/jhgsilva/FPGA_Projects/Tx_Blocks/Numerically_Controlled_Oscillator/Numerically_Controlled_Oscillator.sim/sim_1/behav/xsim/xsim.dir/main_wrapper_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
